# GitHub repository settings
# This file works with the Settings GitHub App: https://github.com/apps/settings
# Install the app to automatically apply these settings to your repository

repository:
  # Basic settings
  name: code-craft-studio
  description: A comprehensive QR code and barcode toolkit for Capacitor applications
  homepage: https://github.com/your-github-username/code-craft-studio
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels to create
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: security
    color: ee0000
    description: Security issue or improvement
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: android
    color: 3ddc84
    description: Android platform specific
  - name: ios
    color: 000000
    description: iOS platform specific
  - name: web
    color: e7e7e7
    description: Web platform specific

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/travis-ci
          - build
          - lint
          - test
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      restrictions:
        users: []
        teams: []
        apps: []
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false
      allow_fork_syncing: true

# Collaborators - Add your team members here
# Replace with actual GitHub usernames
collaborators:
  # Example:
  # - username: teammate1
  #   permission: write
  # - username: reviewer1
  #   permission: triage

# Teams - For organization repositories
teams:
  # Example:
  # - name: core-team
  #   permission: maintain
  # - name: contributors
  #   permission: write